services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        ports:
            - 8880:80
            - 5443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:fPcWRGP3UqEMc0nCI1l9ldZKBtwobyOaZPoKFxnfXsA=
            - APP_DEBUG=true
            - SPEEDTEST_SCHEDULE=0 */1 * * *
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedtest_tracker
            - DB_PASSWORD=password
            - APP_TIMEZONE=Asia/Jakarta
        volumes:
            - speedtest-config:/config
            - speedtest-ssl-keys:/config/keys
        depends_on:
            - db
    db:
        image: mysql:8
        restart: always
        environment:
            - MYSQL_DATABASE=speedtest_tracker
            - MYSQL_USER=speedtest_tracker
            - MYSQL_PASSWORD=password
            - MYSQL_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_PASSWORD}"]
            interval: 5s
            retries: 5
            timeout: 5s
volumes:
    speedtest-db:
    speedtest-config:
    speedtest-ssl-keys:
